### ISSUE TITLE
Readme is out of date

### ISSUE THREAD

**Issue by joelthelion** [intolerable/reddit#10]
For example, the getPosts function has changed, apparently:

    Prelude Reddit> :t Reddit.getPosts
    Reddit.getPosts
      :: Control.Monad.IO.Class.MonadIO m =>
         RedditT m Reddit.Types.Post.PostListing

Also, Reddit.API seems to have been renamed to Reddit.

A simple, complete example would be very useful for newcomers.

**Comment by intolerable** [comment]
yeah the readme is a mess and there's a bunch of documentation missing, i'm gonna try and get it up to a useful state some time this week. i'd like to also get it on hackage but there are one or two big outstanding bugs that need fixed first

**Comment by tejon** [comment]
> one or two big outstanding bugs

#9 seems to be the only one recorded here -- you've got at least two other people paying some attention here, maybe it'd be worth making issues for your entire fix list? :)

Aside @joelthelion -- small world! I've seen you frequently on Slant, keep wanting to ask if your username is a Bowie reference.

**Comment by intolerable** [comment]
i've cleaned up the issue tracker (there's one possible bug that isn't on there because i can't reproduce it) and i'll try to get everything on it fixed at some point this week (probably won't manage oauth soon, though)

**Comment by intolerable** [comment]
it's been updated
