### ISSUE TITLE
Rate limiting appears to be broken

### ISSUE THREAD

**Issue by tejon** [intolerable/reddit#16]
When trying to post from a young account, I got this back:

    Left (APIError (RateLimitError 256 "you are doing that too much. try again in 4 minutes."))

RedditOptions declaration is from `def` with no override for `rateLimitingEnabled`. Just for fun I verified in GHCi that it's `True`.

Haven't looked at the relevant code since pre-Hackage (and honestly not sure where it's tucked away at the moment), but IIRC the rate limit handler should stall the thread instead of returning that error, shouldn't it?

**Comment by intolerable** [comment]
are you using the github version?

**Comment by intolerable** [comment]
i can't reproduce this on the hackage version, but it wouldn't surprise me if the rate limiting was broken on head

**Comment by tejon** [comment]
I'm using it from Hackage, with a version constraint so I know it's not some old version kicking around either. Does it make a difference that this is from a comment, not a post submission?

**Comment by intolerable** [comment]
ok i've got it reproducing now, i'll take a look at it

**Comment by intolerable** [comment]
should be fixed in f50bd84ad613f0c01551dbcccc60cf4bef0a286b (and v0.1.1.0 is now on hackage)

**Comment by tejon** [comment]
Awesome, thanks!

**Comment by intolerable** [comment]
let me know if you run into any more problems
