### ISSUE TITLE
    Module ‘Network.HTTP.Client’ does not export ‘HasHttpManager(..)’

### ISSUE THREAD

**Issue by brsunter** [intolerable/reddit#20]
Getting this during install:

Configuring http-conduit-2.1.8...
Building http-conduit-2.1.8...
Preprocessing library http-conduit-2.1.8...
[1 of 2] Compiling Network.HTTP.Client.Conduit ( Network/HTTP/Client/Conduit.hs, dist/dist-sandbox-1625ed9d/build/Network/HTTP/Client/Conduit.o )

Network/HTTP/Client/Conduit.hs:47:48:
    Module ‘Network.HTTP.Client’ does not export ‘HasHttpManager(..)’
cabal: Error: some packages failed to install:
api-builder-0.9.1.0 depends on http-conduit-2.1.8 which failed to install.
http-conduit-2.1.8 failed during the building phase. The exception was:
ExitFailure 1
reddit-0.1.1.0 depends on http-conduit-2.1.8 which failed to install.

**Comment by intolerable** [comment]
use the github version of this library, there's a problem with http-conduit at the moment (i've submitted a fix for it) which means the version of `reddit` on hackage won't compile

the alternative is giving explicit bounds for http-conduit (2.1.7.*) and http-client (0.4.18.*)

**Comment by tejon** [comment]
`http-conduit == 2.1.7.2` was enough at my end.

**Comment by intolerable** [comment]
it's fixed upstream now, and should be fine
