### ISSUE TITLE
Building with Stack & older packages

### ISSUE THREAD

**Issue by atcol** [intolerable/reddit#27]
Hello.

My default Haskell workflow is to `stack new xx` and begin editing the `.cabal` file for dependency management, but I'm failing to build against your package due to some restrictions. Is there a chance you could update or widen or update the ranges?

Here's my what I'm struggling with:

	$ stack install

	Error: While constructing the build plan, the following exceptions were encountered:

	In the dependencies for xx-0.1.0.0:
			reddit must match -any, but the stack configuration has no specified version (latest applicable is 0.2.1.0)
	needed since xx-0.1.0.0 is a build target.

	Recommended action: try adding the following to your extra-deps in xx/stack.yaml:
	- reddit-0.2.1.0

	You may also want to try the 'stack solver' command
	Plan construction failed.
	$ stack solver --update-config
	Using configuration file: stack.yaml
	Using cabal packages:
	- xx.cabal

	Using resolver: nightly-2017-09-07
	Using compiler: ghc-8.2.1
	Asking cabal to calculate a build plan...
	Trying with packages from nightly-2017-09-07 as hard constraints...
	Attempt failed.

	>>>> Cabal errors begin
	cabal: Could not resolve dependencies:
	trying: xx-0.1.0.0 (user goal)
	trying: base-4.10.0.0/installed-4.1... (dependency of xx-0.1.0.0)
	next goal: reddit (dependency of xx-0.1.0.0)
	rejecting: reddit-0.2.1.0 (conflict: base==4.10.0.0/installed-4.1..., reddit
	=> base>=4.6 && <4.10)
	rejecting: reddit-0.2.0.0, reddit-0.1.1.0, reddit-0.1.0.0 (conflict:
	base==4.10.0.0/installed-4.1..., reddit => base>=4.6 && <4.9)
	Dependency tree exhaustively searched.
	<<<< Cabal errors end

	Retrying with packages from nightly-2017-09-07 as preferences...
	Attempt failed.

	>>>> Cabal errors begin
	cabal: Could not resolve dependencies:
	trying: xx-0.1.0.0 (user goal)
	trying: base-4.10.0.0/installed-4.1... (dependency of xx-0.1.0.0)
	next goal: reddit (dependency of xx-0.1.0.0)
	rejecting: reddit-0.2.1.0 (conflict: base==4.10.0.0/installed-4.1..., reddit
	=> base>=4.6 && <4.10)
	rejecting: reddit-0.2.0.0, reddit-0.1.1.0, reddit-0.1.0.0 (conflict:
	base==4.10.0.0/installed-4.1..., reddit => base>=4.6 && <4.9)
	Dependency tree exhaustively searched.
	<<<< Cabal errors end

	*** Failed to arrive at a workable build plan.

	Solver could not resolve package dependencies.
	You can try the following:
			- Update external packages with 'stack update' and try again.
			- Tweak stack.yaml and try again
					- Remove any unnecessary packages.
					- Add any missing remote packages.
					- Add extra dependencies to guide solver.
					- Adjust resolver.

**Comment by mr** [comment]
`reddit` isn't in Stackage. You need to add it to your `stack.yaml`

    extra-deps:
        - 'reddit-0.2.1.0'

**Comment by atcol** [comment]
Hmm, I thought `stack solver` would sort that out. I'll give it a try...

**Comment by atcol** [comment]
Yeah, it still struggles to find anything in those ranges from a remotely recent stackage version:

		Using resolver: lts-8.24
		Using compiler: ghc-8.0.2
		Asking cabal to calculate a build plan...
		Trying with packages from lts-8.24 and 1 external packages as hard constraints...
		Attempt failed.

		>>>> Cabal errors begin
		cabal: Could not resolve dependencies:
		trying: reddit-0.2.1.0 (dependency of xx-0.1.0.0)
		next goal: aeson (dependency of reddit-0.2.1.0)
		rejecting: aeson-1.2.1.0, aeson-1.2.0.0, aeson-1.1.2.0, aeson-1.1.1.0,
		aeson-1.1.0.0 (constraint from main config /tmp/cabal-solver5459/cabal.config
		requires ==1.0.2.1)
		rejecting: aeson-1.0.2.1 (conflict: reddit => aeson>=0.9 && <0.12)
		rejecting: aeson-1.0.2.0, aeson-1.0.1.0, aeson-1.0.0.0, aeson-0.11.3.0,
		aeson-0.11.2.1, aeson-0.11.2.0, aeson-0.11.1.4, aeson-0.11.1.3,
		aeson-0.11.1.2, aeson-0.11.1.1, aeson-0.11.1.0, aeson-0.11.0.0, aeson-0.9.0.1,
		aeson-0.9.0.0, aeson-0.8.1.1, aeson-0.8.1.0, aeson-0.8.0.2, aeson-0.7.0.6,
		aeson-0.7.0.4, aeson-0.6.2.1, aeson-0.6.2.0, aeson-0.6.1.0, aeson-0.6.0.2,
		aeson-0.6.0.1, aeson-0.6.0.0, aeson-0.5.0.0, aeson-0.4.0.1, aeson-0.4.0.0,
		aeson-0.3.2.14, aeson-0.3.2.13, aeson-0.3.2.12, aeson-0.3.2.11,
		aeson-0.3.2.10, aeson-0.3.2.9, aeson-0.3.2.8, aeson-0.3.2.7, aeson-0.3.2.6,
		aeson-0.3.2.5, aeson-0.3.2.4, aeson-0.3.2.3, aeson-0.3.2.2, aeson-0.3.2.1,
		aeson-0.3.2.0, aeson-0.3.1.1, aeson-0.3.1.0, aeson-0.3.0.0, aeson-0.2.0.0,
		aeson-0.1.0.0, aeson-0.10.0.0, aeson-0.8.0.1, aeson-0.8.0.0, aeson-0.7.0.5,
		aeson-0.7.0.3, aeson-0.7.0.2, aeson-0.7.0.1, aeson-0.7.0.0 (constraint from
		main config /tmp/cabal-solver5459/cabal.config requires ==1.0.2.1)
		Dependency tree exhaustively searched.
		<<<< Cabal errors end

		Could not parse cabal-install errors:

		>>>> Cabal errors begin
		cabal: Could not resolve dependencies:
		trying: reddit-0.2.1.0 (dependency of xx-0.1.0.0)
		next goal: aeson (dependency of reddit-0.2.1.0)
		rejecting: aeson-1.2.1.0, aeson-1.2.0.0, aeson-1.1.2.0, aeson-1.1.1.0,
		aeson-1.1.0.0 (constraint from main config /tmp/cabal-solver5459/cabal.config
		requires ==1.0.2.1)
		rejecting: aeson-1.0.2.1 (conflict: reddit => aeson>=0.9 && <0.12)
		rejecting: aeson-1.0.2.0, aeson-1.0.1.0, aeson-1.0.0.0, aeson-0.11.3.0,
		aeson-0.11.2.1, aeson-0.11.2.0, aeson-0.11.1.4, aeson-0.11.1.3,
		aeson-0.11.1.2, aeson-0.11.1.1, aeson-0.11.1.0, aeson-0.11.0.0, aeson-0.9.0.1,
		aeson-0.9.0.0, aeson-0.8.1.1, aeson-0.8.1.0, aeson-0.8.0.2, aeson-0.7.0.6,
		aeson-0.7.0.4, aeson-0.6.2.1, aeson-0.6.2.0, aeson-0.6.1.0, aeson-0.6.0.2,
		aeson-0.6.0.1, aeson-0.6.0.0, aeson-0.5.0.0, aeson-0.4.0.1, aeson-0.4.0.0,
		aeson-0.3.2.14, aeson-0.3.2.13, aeson-0.3.2.12, aeson-0.3.2.11,
		aeson-0.3.2.10, aeson-0.3.2.9, aeson-0.3.2.8, aeson-0.3.2.7, aeson-0.3.2.6,
		aeson-0.3.2.5, aeson-0.3.2.4, aeson-0.3.2.3, aeson-0.3.2.2, aeson-0.3.2.1,
		aeson-0.3.2.0, aeson-0.3.1.1, aeson-0.3.1.0, aeson-0.3.0.0, aeson-0.2.0.0,
		aeson-0.1.0.0, aeson-0.10.0.0, aeson-0.8.0.1, aeson-0.8.0.0, aeson-0.7.0.5,
		aeson-0.7.0.3, aeson-0.7.0.2, aeson-0.7.0.1, aeson-0.7.0.0 (constraint from
		main config /tmp/cabal-solver5459/cabal.config requires ==1.0.2.1)
		Dependency tree exhaustively searched.
		<<<< Cabal errors end

		CallStack (from HasCallStack):
			error, called at src/Stack/Solver.hs:144:25 in stack-1.5.1-8L0HpUwgvNa7pLuInyRw8N:Stack.Solver

**Comment by atcol** [comment]
Hello :)

Don't suppose you've had a chance to look at this, or know what I might be able to start with in order to help out?

**Comment by intolerable** [comment]
sorry for the (glacially) slow response -- it should be possible to get the library running with a recent version of stack now!

**Comment by intolerable** [comment]
let me know if you run into any issues, though

**Comment by atcol** [comment]
Happy new year! Thanks for the update.

I created a fresh project and added `reddit` to my executable's `dependencies` section in `package.yaml`:

    dependencies:
    - rd
    - reddit

Then it needed this library to be added to the `stack.yaml` so I  did `stack solver --update-config` and it added this:

```
$ cat stack.yaml
flags: {}
packages:
- .
extra-deps:
- api-builder-0.14.0.0
- reddit-0.2.2.1
resolver: lts-10.3
```

I then ran `stack install` and it failed to compile `reddit-0.2.2.1` because:

reddit-0.2.2.1: configure
reddit-0.2.2.1: build

--  While building custom Setup.hs for package reddit-0.2.2.1 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_2.0.1.0_ghc-8.2.2.exe --builddir=.stack-work\dist\5c8418a7 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: D:\atc\AppData\Local\Temp\rd\.stack-work\logs\reddit-0.2.2.1.log

    Configuring reddit-0.2.2.1...
    Preprocessing library for reddit-0.2.2.1..
    Building library for reddit-0.2.2.1..
    [ 1 of 49] Compiling Paths_reddit     ( .stack-work\dist\5c8418a7\build\autogen\Paths_reddit.hs, .stack-work\dist\5c8418a7\build\Paths_reddit.o )
    [ 2 of 49] Compiling Reddit.Parser    ( src\Reddit\Parser.hs, .stack-work\dist\5c8418a7\build\Reddit\Parser.o )
    [ 3 of 49] Compiling Reddit.Types.Empty ( src\Reddit\Types\Empty.hs, .stack-work\dist\5c8418a7\build\Reddit\Types\Empty.o )
    [ 4 of 49] Compiling Reddit.Types.Error ( src\Reddit\Types\Error.hs, .stack-work\dist\5c8418a7\build\Reddit\Types\Error.o )
    [ 5 of 49] Compiling Reddit.Types.Listing ( src\Reddit\Types\Listing.hs, .stack-work\dist\5c8418a7\build\Reddit\Types\Listing.o )
    [ 6 of 49] Compiling Reddit.Types.Options ( src\Reddit\Types\Options.hs, .stack-work\dist\5c8418a7\build\Reddit\Types\Options.o )
    [ 7 of 49] Compiling Reddit.Types.Reddit ( src\Reddit\Types\Reddit.hs, .stack-work\dist\5c8418a7\build\Reddit\Types\Reddit.o )
    [ 8 of 49] Compiling Reddit.Types.Captcha ( src\Reddit\Types\Captcha.hs, .stack-work\dist\5c8418a7\build\Reddit\Types\Captcha.o )
    [ 9 of 49] Compiling Reddit.Routes.Captcha ( src\Reddit\Routes\Captcha.hs, .stack-work\dist\5c8418a7\build\Reddit\Routes\Captcha.o )
    [10 of 49] Compiling Reddit.Login     ( src\Reddit\Login.hs, .stack-work\dist\5c8418a7\build\Reddit\Login.o )
    [11 of 49] Compiling Reddit.Actions.Captcha ( src\Reddit\Actions\Captcha.hs, .stack-work\dist\5c8418a7\build\Reddit\Actions\Captcha.o )
    [12 of 49] Compiling Reddit.Types.SearchOptions ( src\Reddit\Types\SearchOptions.hs, .stack-work\dist\5c8418a7\build\Reddit\Types\SearchOptions.o )
    [13 of 49] Compiling Reddit.Types.Thing ( src\Reddit\Types\Thing.hs, .stack-work\dist\5c8418a7\build\Reddit\Types\Thing.o )
    [14 of 49] Compiling Reddit.Types.Subreddit ( src\Reddit\Types\Subreddit.hs, .stack-work\dist\5c8418a7\build\Reddit\Types\Subreddit.o )
    [15 of 49] Compiling Reddit.Routes.Wiki ( src\Reddit\Routes\Wiki.hs, .stack-work\dist\5c8418a7\build\Reddit\Routes\Wiki.o )
    [16 of 49] Compiling Reddit.Routes.Vote ( src\Reddit\Routes\Vote.hs, .stack-work\dist\5c8418a7\build\Reddit\Routes\Vote.o )
    [17 of 49] Compiling Reddit.Routes.Thing ( src\Reddit\Routes\Thing.hs, .stack-work\dist\5c8418a7\build\Reddit\Routes\Thing.o )
    [18 of 49] Compiling Reddit.Types.User ( src\Reddit\Types\User.hs, .stack-work\dist\5c8418a7\build\Reddit\Types\User.o )
    [19 of 49] Compiling Reddit.Types.Moderation ( src\Reddit\Types\Moderation.hs, .stack-work\dist\5c8418a7\build\Reddit\Types\Moderation.o )
    [20 of 49] Compiling Reddit.Types.Flair ( src\Reddit\Types\Flair.hs, .stack-work\dist\5c8418a7\build\Reddit\Types\Flair.o )
    [21 of 49] Compiling Reddit.Routes.Flair ( src\Reddit\Routes\Flair.hs, .stack-work\dist\5c8418a7\build\Reddit\Routes\Flair.o )
    [22 of 49] Compiling Reddit.Actions.Flair ( src\Reddit\Actions\Flair.hs, .stack-work\dist\5c8418a7\build\Reddit\Actions\Flair.o )

    D:\atc\AppData\Local\Temp\stack19184\reddit-0.2.2.1\src\Reddit\Actions\Flair.hs:28:29: error:
        Ambiguous occurrence `Options'
        It could refer to either `Reddit.Types.Options.Options',
                                 imported from `Reddit.Types.Options' at src\Reddit\Actions\Flair.hs:11:1-27
                                 (and originally defined
                                    at src\Reddit\Types\Options.hs:(9,1)-(11,27))
                              or `Data.Aeson.Options',
                                 imported from `Data.Aeson' at src\Reddit\Actions\Flair.hs:17:1-17
                                 (and originally defined in `aeson-1.2.3.0:Data.Aeson.Types.Internal')
       |
    28 | getFlairList' :: Monad m => Options UserID -> SubredditName -> RedditT m FlairListing
       |                             ^^^^^^^

Am I doing anything wrong?

**Comment by intolerable** [comment]
my mistake! i didn't have the right version of stack installed, but i've fixed the problem and pushed a new version of the library to hackage (0.2.2.2) and it should work now!!

let me know if you run into any other trouble

**Comment by atcol** [comment]
It works. Had to set the explicit version in `stack.yaml` of course.

Thanks!

**Comment by intolerable** [comment]
no problem! thanks for helping me to get this solved!
