### ISSUE TITLE
Not on Hackage

### ISSUE THREAD

**Issue by tejon** [intolerable/reddit#8]
Which would bug me less if I could get the haddocks to build locally. :P

**Comment by intolerable** [comment]
what problem are you having with getting the haddocks to render? they work fine for me

the library itself isnt ready for hackage just yet

**Comment by tejon** [comment]
I did finally get haddocks working. Mainly this issue serves as
notification that someone is actually using the module. :)

**Comment by intolerable** [comment]
we are now on hackage: https://hackage.haskell.org/package/reddit :smile:
